#!/usr/bin/env python

import sys
from xml.sax.saxutils import escape

if len(sys.argv) != 3:
    print "Usage: {0} <input> <output>\n".format(sys.argv[0])
    sys.exit(1)

with open(sys.argv[1]) as f_in:
    with open(sys.argv[2], "w") as f_out:
        f_out.write("<html><body><pre>" + escape(f_in.read()) +
                        "</pre></body></html>")
